// lib/features/logbook/data/models/glucose_log_model.dart
import 'package:hive/hive.dart';
import '../../domain/entities/glucose_log.dart';

part 'glucose_log_model.g.dart'; // Generated by build_runner for Hive

@HiveType(typeId: 0)
class GlucoseLogModel extends GlucoseLog {
  @HiveField(0)
  final String id;
  @HiveField(1)
  final String patientId;
  @HiveField(2)
  final DateTime localTimestamp;
  @HiveField(3)
  final int glucoseMgdl;
  @HiveField(4)
  final double insulinUnits;
  @HiveField(5)
  final int carbsGrams;
  @HiveField(6)
  final List<String> contextTags;
  @HiveField(7)
  final String? localPhotoPath;
  @HiveField(8)
  final String? cloudPhotoUrl;
  @HiveField(9)
  final bool isSynced;

  GlucoseLogModel({
    required this.id,
    required this.patientId,
    required this.localTimestamp,
    required this.glucoseMgdl,
    required this.insulinUnits,
    required this.carbsGrams,
    required this.contextTags,
    this.localPhotoPath,
    this.cloudPhotoUrl,
    required this.isSynced,
  }) : super(
          id: id,
          patientId: patientId,
          localTimestamp: localTimestamp,
          glucoseMgdl: glucoseMgdl,
          insulinUnits: insulinUnits,
          carbsGrams: carbsGrams,
          contextTags: contextTags,
          localPhotoPath: localPhotoPath,
          cloudPhotoUrl: cloudPhotoUrl,
          isSynced: isSynced,
        );

  /// Factory to convert Domain Entity to Data Model
  factory GlucoseLogModel.fromEntity(GlucoseLog entity) {
    return GlucoseLogModel(
      id: entity.id,
      patientId: entity.patientId,
      localTimestamp: entity.localTimestamp,
      glucoseMgdl: entity.glucoseMgdl,
      insulinUnits: entity.insulinUnits,
      carbsGrams: entity.carbsGrams,
      contextTags: entity.contextTags,
      localPhotoPath: entity.localPhotoPath,
      cloudPhotoUrl: entity.cloudPhotoUrl,
      isSynced: entity.isSynced,
    );
  }

  /// Map from FHIR-inspired JSON payload
  factory GlucoseLogModel.fromJson(Map<String, dynamic> json) {
    return GlucoseLogModel(
      id: json['resource_id'] as String,
      patientId: json['subject_id'] as String,
      localTimestamp: DateTime.parse(json['effective_datetime'] as String),
      glucoseMgdl: json['observation_glucose_mgdl'] as int,
      insulinUnits: (json['medication_insulin_units'] as num).toDouble(),
      carbsGrams: json['nutrition_carbs_grams'] as int,
      contextTags: List<String>.from(json['context_tags'] ?? []),
      localPhotoPath: json['local_photo_path'] as String?,
      cloudPhotoUrl: json['cloud_photo_url'] as String?,
      isSynced: json['is_synced'] as bool? ?? true,
    );
  }

  /// Map to FHIR-inspired JSON payload for Cloud Firestore
  Map<String, dynamic> toJson() {
    return {
      'resource_id': id,
      'subject_id': patientId,
      'effective_datetime': localTimestamp.toIso8601String(),
      'observation_glucose_mgdl': glucoseMgdl,
      'medication_insulin_units': insulinUnits,
      'nutrition_carbs_grams': carbsGrams,
      'context_tags': contextTags,
      'local_photo_path': localPhotoPath,
      'cloud_photo_url': cloudPhotoUrl,
      'is_synced': isSynced,
    };
  }
}